familyName: Frex Sans GB
buildVariable: false # set to false because Text weight missing
buildStatic: true

# For static builds
buildTTF: true
buildOTF: true
buildWebfont: true
autohintTTF: false
autohintOTF: false

# For variable builds
# stat:
#     - name: Weight
#       tag: wght
#       values:
#           - name: Thin
#             value: 100
#           - name: ExtraLight
#             value: 200
#           - name: Light
#             value: 300
#           - name: Regular
#             value: 400
#             flags: 2
#             linkedValue: 700
#           - name: Text
#             value: 450
#           - name: Medium
#             value: 500
#           - name: SemiBold
#             value: 600
#           - name: Bold
#             value: 700

# Output directory
outputDir: ../../fonts

# source file
sources:
    - Frex Sans GB.designspace
